name:                           Check

on:
  pull_request:
  push:
    branches:
      - main
      - dev
jobs:
  check:
    name:                       Check
    runs-on:                    ubuntu-22.04
    steps:
      - name:                   Checkout sources
        uses:                   actions/checkout@main
        with:
          submodules:           true
      - name:                   Install 1.59 toolchain
        uses:                   actions-rs/toolchain@v1
        with:
          toolchain:            1.85
          profile:              minimal
          override:             true
      - name:                   Run cargo check
        uses:                   actions-rs/cargo@v1
        with:
          command:              check
          args:                 --locked --all --benches --verbose --tests
      - name:                   Run validate chainspecs
        run:                    ./scripts/actions/validate-chainspecs.sh
          args:                 --locked --all --benches --verbose --tests

